export const REQUEST_MOVIE_LIST = 'REQUEST_MOVIE_LIST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE';
export const REQUEST_NEXT_PAGE = 'REQUEST_NEXT_PAGE';
